name: api key add

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Replace API Key
        run: |
          sed -i "s|\${GOOGLE_MAPS_API_KEY}|${{ secrets.GOOGLE_MAPS_API_KEY }}|g" index.html